name: Developer_Pull_Request
on:
  workflow_call:
    inputs:
      service_name:
        type: string
        required: true
jobs:
  CI_Steps:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unit Tests
        run: echo Unit Tests

      - name: Integration Tests
        run: echo Integration Tests

      - name: SAST Scans
        run: echo SAST Scans

      - name: Detect Secrets in Source Code
        run: echo ## trufflehog filesystem .

      - name: Code Quality
        shell: bash
        run: sonar-scanner -Dsonar.host.url=http://sonarqube-int.rdevopsb73.online:9000 -Dsonar.login="${SONAR_USER}" -Dsonar.password="${SONAR_PASS}" -Dsonar.projectKey=${service_name} -Dsonar.qualitygate.wait=true
        env:
          SONAR_USER: ${{ secrets.SONAR_USER }}
          SONAR_PASS: ${{ secrets.SONAR_PASS }}
          service_name: ${{ inputs.service_name }}




