name: Developer_Branch_CI
on: [workflow_call]
jobs:
  CI_Steps:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unit Tests
        run: echo npm test

      - name: Integration Tests
        run: echo Integration Tests

      - name: Code Quality & Quality Gate
        shell: bash
        run: sonar-scanner -Dsonar.host.url=http://sonarqube-int.rdevopsb73.online:9000 -Dsonar.login="${SONAR_USER}" -Dsonar.password="${SONAR_PASS}" -Dsonar.projectKey=$service_name
        env:
          SONAR_USER: ${{ secrets.SONAR_USER }}
          SONAR_PASS: ${{ secrets.SONAR_PASS }}




