name: Release_Tags
on:
  workflow_call:
    inputs:
      service_name:
        type: string
        required: true
jobs:
  CI_Steps:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SAST Scans
        run: echo SAST Scans

      - name: SCA Scans
        run: echo SCA Scans

      - name: Detect Secrets in Source Code
        run: echo Detect Secrets in Source Code

      - name: Download Dependencies
        if: inputs.service_name == 'expense-backend'
        run: npm install

      - name: Produce Artifact
        env:
          service_name: ${{ inputs.service_name }}
          ARTIFACTORY_CREDENTIALS: ${{ secrets.ARTIFACTORY_CREDENTIALS }}
        run: |
          zip -r ${GITHUB_REF_NAME}.zip * -x .github
          curl -f -v -X PUT -u ${ARTIFACTORY_CREDENTIALS} -T ${GITHUB_REF_NAME}.zip http://artifactory-int.rdevopsb73.online:8081/artifactory/${service_name}/${GITHUB_REF_NAME}.zip



