name: Reusable Workflow
on: [push, pull_request, workflow_call]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: echo SAST Scans
